package com.rl.web.inter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2014-05-13T14:15:52.440+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://inter.server.web.rl.com/", name = "ByeInter")
@XmlSeeAlso({ObjectFactory.class})
public interface ByeInter {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayBye", targetNamespace = "http://inter.server.web.rl.com/", className = "com.rl.web.inter.SayBye")
    @WebMethod
    @ResponseWrapper(localName = "sayByeResponse", targetNamespace = "http://inter.server.web.rl.com/", className = "com.rl.web.inter.SayByeResponse")
    public java.lang.String sayBye(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
