package com.rl.spring;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2014-05-13T16:32:16.118+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "PersonServiceWSService", 
                  wsdlLocation = "http://localhost:8080/spring_cxf/service/person?wsdl",
                  targetNamespace = "http://service.ws.person.rl.com/") 
public class PersonServiceWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.person.rl.com/", "PersonServiceWSService");
    public final static QName PersonServiceWSPort = new QName("http://service.ws.person.rl.com/", "PersonServiceWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/spring_cxf/service/person?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PersonServiceWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/spring_cxf/service/person?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonServiceWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonServiceWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonServiceWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonServiceWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonServiceWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonServiceWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PersonServiceWS
     */
    @WebEndpoint(name = "PersonServiceWSPort")
    public PersonServiceWS getPersonServiceWSPort() {
        return super.getPort(PersonServiceWSPort, PersonServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonServiceWS
     */
    @WebEndpoint(name = "PersonServiceWSPort")
    public PersonServiceWS getPersonServiceWSPort(WebServiceFeature... features) {
        return super.getPort(PersonServiceWSPort, PersonServiceWS.class, features);
    }

}
