package com.rl.spring;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2014-05-13T16:32:16.081+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.ws.person.rl.com/", name = "PersonServiceWS")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonServiceWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPersonAll", targetNamespace = "http://service.ws.person.rl.com/", className = "com.rl.spring.GetPersonAll")
    @WebMethod
    @ResponseWrapper(localName = "getPersonAllResponse", targetNamespace = "http://service.ws.person.rl.com/", className = "com.rl.spring.GetPersonAllResponse")
    public java.util.List<com.rl.spring.Person> getPersonAll();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.ws.person.rl.com/", className = "com.rl.spring.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.ws.person.rl.com/", className = "com.rl.spring.AddResponse")
    public java.lang.String add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.rl.spring.Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
