
package liang.ren.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MyHelloServer", targetNamespace = "hello.ren.liang")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyHelloServer {


    /**
     * 
     * @param personName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "byeResult", targetNamespace = "")
    @RequestWrapper(localName = "sayBye", targetNamespace = "hello.ren.liang", className = "liang.ren.hello.SayBye")
    @ResponseWrapper(localName = "sayByeResponse", targetNamespace = "hello.ren.liang", className = "liang.ren.hello.SayByeResponse")
    public String sayBye(
        @WebParam(name = "personName", targetNamespace = "")
        String personName);

}
