
package liang.ren.hello;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MyHelloServerService", targetNamespace = "hello.ren.liang", wsdlLocation = "http://127.0.0.1:8080/hello?wsdl")
public class MyHelloServerService
    extends Service
{

    private final static URL MYHELLOSERVERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(liang.ren.hello.MyHelloServerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = liang.ren.hello.MyHelloServerService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/hello?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/hello?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MYHELLOSERVERSERVICE_WSDL_LOCATION = url;
    }

    public MyHelloServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyHelloServerService() {
        super(MYHELLOSERVERSERVICE_WSDL_LOCATION, new QName("hello.ren.liang", "MyHelloServerService"));
    }

    /**
     * 
     * @return
     *     returns MyHelloServer
     */
    @WebEndpoint(name = "MyHelloServer")
    public MyHelloServer getMyHelloServer() {
        return super.getPort(new QName("hello.ren.liang", "MyHelloServer"), MyHelloServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyHelloServer
     */
    @WebEndpoint(name = "MyHelloServer")
    public MyHelloServer getMyHelloServer(WebServiceFeature... features) {
        return super.getPort(new QName("hello.ren.liang", "MyHelloServer"), MyHelloServer.class, features);
    }

}
