
package com.rl.person;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PersonServerService", targetNamespace = "http://server.rl.com/", wsdlLocation = "http://127.0.0.1:6060/person?wsdl")
public class PersonServerService
    extends Service
{

    private final static URL PERSONSERVERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.rl.person.PersonServerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.rl.person.PersonServerService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:6060/person?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:6060/person?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PERSONSERVERSERVICE_WSDL_LOCATION = url;
    }

    public PersonServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonServerService() {
        super(PERSONSERVERSERVICE_WSDL_LOCATION, new QName("http://server.rl.com/", "PersonServerService"));
    }

    /**
     * 
     * @return
     *     returns PersonServer
     */
    @WebEndpoint(name = "PersonServerPort")
    public PersonServer getPersonServerPort() {
        return super.getPort(new QName("http://server.rl.com/", "PersonServerPort"), PersonServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonServer
     */
    @WebEndpoint(name = "PersonServerPort")
    public PersonServer getPersonServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.rl.com/", "PersonServerPort"), PersonServer.class, features);
    }

}
