
package com.rl.person;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PersonServer", targetNamespace = "http://server.rl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonServer {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://server.rl.com/", className = "com.rl.person.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://server.rl.com/", className = "com.rl.person.AddPersonResponse")
    public void addPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.rl.person.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonAll", targetNamespace = "http://server.rl.com/", className = "com.rl.person.GetPersonAll")
    @ResponseWrapper(localName = "getPersonAllResponse", targetNamespace = "http://server.rl.com/", className = "com.rl.person.GetPersonAllResponse")
    public List<Person> getPersonAll();

}
